//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRLog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppDBEntities : DbContext
    {
        public AppDBEntities()
            : base("name=AppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autenticaciones> Autenticaciones { get; set; }
        public virtual DbSet<Disciplinas> Disciplinas { get; set; }
        public virtual DbSet<Fichas> Fichas { get; set; }
        public virtual DbSet<Gimnasios> Gimnasios { get; set; }
        public virtual DbSet<Horarios> Horarios { get; set; }
        public virtual DbSet<Membresias> Membresias { get; set; }
        public virtual DbSet<PerfilesEntrenadores> PerfilesEntrenadores { get; set; }
        public virtual DbSet<Registros> Registros { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Administradores> Administradores { get; set; }
        public virtual DbSet<Mensualidades> Mensualidades { get; set; }
    }
}
