//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fichas
    {
        public decimal id { get; set; }
        public string EmergenciaNombre1 { get; set; }
        public string EmergenciaApellido1 { get; set; }
        public string EmergenciaCelular1 { get; set; }
        public string EmergenciaEmail1 { get; set; }
        public string EmergenciaNombre2 { get; set; }
        public string EmergenciaApellido2 { get; set; }
        public string EmergenciaCelular2 { get; set; }
        public string EmergenciaEmail2 { get; set; }
        public string TipoSangre { get; set; }
        public string Alergias { get; set; }
        public string Lesiones { get; set; }
        public Nullable<decimal> idUsuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
