//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gimnasios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gimnasios()
        {
            this.Disciplinas = new HashSet<Disciplinas>();
            this.Administradores = new HashSet<Administradores>();
        }
    
        public decimal id { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Pais { get; set; }
        public string Direccion { get; set; }
        public string PersonaContacto { get; set; }
        public string CelularContacto { get; set; }
        public string EmailContacto { get; set; }
        public string ColorPrimario { get; set; }
        public string ColorSecundario { get; set; }
        public string Logo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disciplinas> Disciplinas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Administradores> Administradores { get; set; }
    }
}
