//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recurso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRLog.Recursos.Recurso", typeof(Recurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso denegado al elemento.
        /// </summary>
        public static string AccesoDenegado {
            get {
                return ResourceManager.GetString("AccesoDenegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuéntanos acerca de ti.
        /// </summary>
        public static string AcercaDeTi {
            get {
                return ResourceManager.GetString("AcercaDeTi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesiones, espectativas, otros....
        /// </summary>
        public static string AcercaDeTiTemas {
            get {
                return ResourceManager.GetString("AcercaDeTiTemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar.
        /// </summary>
        public static string Activar {
            get {
                return ResourceManager.GetString("Activar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración.
        /// </summary>
        public static string Administracion {
            get {
                return ResourceManager.GetString("Administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar usuarios.
        /// </summary>
        public static string AdministraUsuarios {
            get {
                return ResourceManager.GetString("AdministraUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altura.
        /// </summary>
        public static string Altura {
            get {
                return ResourceManager.GetString("Altura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar.
        /// </summary>
        public static string Aplicar {
            get {
                return ResourceManager.GetString("Aplicar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de contraseña.
        /// </summary>
        public static string CambioContrasena {
            get {
                return ResourceManager.GetString("CambioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string Celular {
            get {
                return ResourceManager.GetString("Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi numero de celular es público en mi perfil.
        /// </summary>
        public static string CelularPublico {
            get {
                return ResourceManager.GetString("CelularPublico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma contraseña nueva.
        /// </summary>
        public static string ConfirmaContrasena {
            get {
                return ResourceManager.GetString("ConfirmaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actual.
        /// </summary>
        public static string ContrasenaActual {
            get {
                return ResourceManager.GetString("ContrasenaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creado.
        /// </summary>
        public static string Creado {
            get {
                return ResourceManager.GetString("Creado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visita la Galería de programas y escoge el que más se acomode a tus necesidades..
        /// </summary>
        public static string DescripcionGaleria {
            get {
                return ResourceManager.GetString("DescripcionGaleria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Entrar {
            get {
                return ResourceManager.GetString("Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrenamientos.
        /// </summary>
        public static string Entrenamientos {
            get {
                return ResourceManager.GetString("Entrenamientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña y confirmación deben ser iguales..
        /// </summary>
        public static string ErrorConfirmaContrasena {
            get {
                return ResourceManager.GetString("ErrorConfirmaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Los días deben ser mínimo 1..
        /// </summary>
        public static string ErrorDiasMayores {
            get {
                return ResourceManager.GetString("ErrorDiasMayores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese una dirección de correo correcta..
        /// </summary>
        public static string ErrorEmail {
            get {
                return ResourceManager.GetString("ErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: La fecha de fin no puede ser previa a la fecha inicial..
        /// </summary>
        public static string ErrorFechaInicioFin {
            get {
                return ResourceManager.GetString("ErrorFechaInicioFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error no reconocido..
        /// </summary>
        public static string ErrorNoReconocido {
            get {
                return ResourceManager.GetString("ErrorNoReconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Email existente.
        /// </summary>
        public static string ErrorUsuarioExistente {
            get {
                return ResourceManager.GetString("ErrorUsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Usuario y/o contraseña incorrecta.
        /// </summary>
        public static string ErrorUsuarioNoEncontrado {
            get {
                return ResourceManager.GetString("ErrorUsuarioNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: El valor no puede ser negativo..
        /// </summary>
        public static string ErrorValorNegativo {
            get {
                return ResourceManager.GetString("ErrorValorNegativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Espanol {
            get {
                return ResourceManager.GetString("Espanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario desde.
        /// </summary>
        public static string FechaCreacionUsuario {
            get {
                return ResourceManager.GetString("FechaCreacionUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha final.
        /// </summary>
        public static string FechaFinal {
            get {
                return ResourceManager.GetString("FechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de inicio.
        /// </summary>
        public static string FechaInicio {
            get {
                return ResourceManager.GetString("FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        public static string FechaNacimiento {
            get {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoy es un grandioso día..
        /// </summary>
        public static string FraseBienvenida {
            get {
                return ResourceManager.GetString("FraseBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galería de Programas.
        /// </summary>
        public static string GaleriaProgramas {
            get {
                return ResourceManager.GetString("GaleriaProgramas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Hola!.
        /// </summary>
        public static string Hola {
            get {
                return ResourceManager.GetString("Hola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hombre.
        /// </summary>
        public static string Hombre {
            get {
                return ResourceManager.GetString("Hombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciales.
        /// </summary>
        public static string Iniciales {
            get {
                return ResourceManager.GetString("Iniciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitación.
        /// </summary>
        public static string Invitacion {
            get {
                return ResourceManager.GetString("Invitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilos.
        /// </summary>
        public static string Kilos {
            get {
                return ResourceManager.GetString("Kilos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libras.
        /// </summary>
        public static string Libras {
            get {
                return ResourceManager.GetString("Libras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string LoginContrasena {
            get {
                return ResourceManager.GetString("LoginContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compartiremos su email con nadie..
        /// </summary>
        public static string LoginNoCompartiremos {
            get {
                return ResourceManager.GetString("LoginNoCompartiremos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar de entrenamiento.
        /// </summary>
        public static string LugarEntrenamiento {
            get {
                return ResourceManager.GetString("LugarEntrenamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimnasio, box de CrossFit, Club deportivo....
        /// </summary>
        public static string LugarEntrenamientoEjemplo {
            get {
                return ResourceManager.GetString("LugarEntrenamientoEjemplo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string MenuInicio {
            get {
                return ResourceManager.GetString("MenuInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string MenuPerfil {
            get {
                return ResourceManager.GetString("MenuPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mujer.
        /// </summary>
        public static string Mujer {
            get {
                return ResourceManager.GetString("Mujer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña.
        /// </summary>
        public static string NuevaContrasena {
            get {
                return ResourceManager.GetString("NuevaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcional.
        /// </summary>
        public static string Opcional {
            get {
                return ResourceManager.GetString("Opcional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro.
        /// </summary>
        public static string Otro {
            get {
                return ResourceManager.GetString("Otro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausado.
        /// </summary>
        public static string Pausado {
            get {
                return ResourceManager.GetString("Pausado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausar.
        /// </summary>
        public static string Pausar {
            get {
                return ResourceManager.GetString("Pausar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programa.
        /// </summary>
        public static string Programa {
            get {
                return ResourceManager.GetString("Programa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programar.
        /// </summary>
        public static string Programar {
            get {
                return ResourceManager.GetString("Programar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programas.
        /// </summary>
        public static string Programas {
            get {
                return ResourceManager.GetString("Programas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Público.
        /// </summary>
        public static string Publico {
            get {
                return ResourceManager.GetString("Publico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuerdame.
        /// </summary>
        public static string Recuerdame {
            get {
                return ResourceManager.GetString("Recuerdame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requerido para calculos.
        /// </summary>
        public static string RequeridoParaCalculos {
            get {
                return ResourceManager.GetString("RequeridoParaCalculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requiere una altura válida (es utilizado para cálculos).
        /// </summary>
        public static string RequiereAlturaValida {
            get {
                return ResourceManager.GetString("RequiereAlturaValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requiere un apellido válido.
        /// </summary>
        public static string RequiereApellidoValido {
            get {
                return ResourceManager.GetString("RequiereApellidoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requiere una fecha de nacimiento válida.
        /// </summary>
        public static string RequiereFechaNacimientoValida {
            get {
                return ResourceManager.GetString("RequiereFechaNacimientoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requiere un nickname válido.
        /// </summary>
        public static string RequiereNicknameValido {
            get {
                return ResourceManager.GetString("RequiereNicknameValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requiere un nombre válido.
        /// </summary>
        public static string RequiereNombreValido {
            get {
                return ResourceManager.GetString("RequiereNombreValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requiere un sexo válido (es utlizado para cálculos).
        /// </summary>
        public static string RequiereSexoValido {
            get {
                return ResourceManager.GetString("RequiereSexoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Sexo {
            get {
                return ResourceManager.GetString("Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Incribirme ya!.
        /// </summary>
        public static string SolicitarInscribirse {
            get {
                return ResourceManager.GetString("SolicitarInscribirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar más información.
        /// </summary>
        public static string SolicitarMasInfo {
            get {
                return ResourceManager.GetString("SolicitarMasInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de inscripcion a.
        /// </summary>
        public static string SolicitudInscripcionA {
            get {
                return ResourceManager.GetString("SolicitudInscripcionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminado.
        /// </summary>
        public static string Terminado {
            get {
                return ResourceManager.GetString("Terminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Términos y condiciones.
        /// </summary>
        public static string TerminosCondiciones {
            get {
                return ResourceManager.GetString("TerminosCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad de peso.
        /// </summary>
        public static string UnidadPeso {
            get {
                return ResourceManager.GetString("UnidadPeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitar.
        /// </summary>
        public static string Visitar {
            get {
                return ResourceManager.GetString("Visitar", resourceCulture);
            }
        }
    }
}
